#!/usr/bin/python
import socket, sys, os, datetime

HOST = 'xml1.aspsms.com' 
PORT = 5061 

SENT='/home/pi/logs/sms_sent'

sent = open(os.path.join(SENT, datetime.datetime.now().isoformat().replace(':', '-')), 'w')

sys.path.insert(0, '/home/pi')
import credentials as cred

userkey = cred.userkey
password = cred.password
originator = 'schokokeks'

def die(error):
  global sent
  sent.write(error)
  sent.close()
  print error
  sys.exit(1)


valid_prefixes = [ '151', '160', '170', '171', '175', # T-Mobile
                   '152', '162', '172', '173', '174', # Vodafone
                   '157', '163', '177', '178', # E-Plus
                   '176', '179', # O2
                 ]


if len(sys.argv) < 3:
  die('usage: %s <number> <text>' % sys.argv[0])

recipient = sys.argv[1]

if recipient.startswith('01'):
  recipient = '+49'+recipient[1:]

if not recipient.startswith('+49'):
  die('must be a recipient in germany')
if recipient[3:6] not in valid_prefixes:
  die('unknown or unsupported operator')
  

text = sys.argv[2]

if len(text) > 160:
  text = text[:160]

text = text.replace('<', '&lt;').replace('>', '&gt;')

CONTENT="""<?xml version="1.0" encoding="UTF-8"?>
<aspsms>
  <Userkey>"""+str(userkey)+"""</Userkey>
  <Password>"""+str(password)+"""</Password>
  <Originator>"""+ str(originator) +"""</Originator>
  <Recipient>
    <PhoneNumber>"""+ str(recipient) +"""</PhoneNumber>
  </Recipient>
  <MessageData>"""+ str(text) +"""</MessageData>
  <Action>SendTextSMS</Action>
</aspsms>
"""

sent.write(CONTENT)

length=len(CONTENT)
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))
s.send("POST /xmlsvr.asp HTTP/1.0\r\n")
s.send("Content-Type: text/xml\r\n")
s.send("Content-Length: "+str(length)+"\r\n\r\n")
s.send(CONTENT)
datarecv=s.recv(1024)
sent.write('''
Reply Received: 
'''+ str(datarecv))
s.close()
sent.close()
