#!/usr/bin/python
import requests, sys, os, datetime, json

HOST = 'xml1.aspsms.com' 
PORT = 5061 

SENT='/home/bernd/logs/sms_sent'

sys.path.insert(0, '/home/bernd')
import credentials as cred

userkey = cred.userkey
password = cred.password
originator = 'Heizung'

def die(error):
  global sent
  sent.write(error)
  sent.close()
  print(error)
  sys.exit(1)


valid_prefixes = [ '151', '160', '170', '171', '175', # T-Mobile
                   '152', '162', '172', '173', '174', # Vodafone
                   '157', '163', '177', '178', # E-Plus
                   '176', '179', # O2
                 ]


if len(sys.argv) < 3:
  die('usage: %s <number> <text>' % sys.argv[0])

recipient = sys.argv[1]

if recipient.startswith('01'):
  recipient = '+49'+recipient[1:]

if not recipient.startswith('+49'):
  die('must be a recipient in germany')
if recipient[3:6] not in valid_prefixes:
  die('unknown or unsupported operator')
  

text = sys.argv[2]


if len(text) > 160:
    text = text[:160]

# ASPSMS
headers = {
    'Accept': 'application/json',
}
url = 'https://json.aspsms.com/SendTextSMS'
data = {
    "UserName": cred.userkey,
    "Password": cred.password,
    "Originator": 'Heizung',
    "Recipients": [recipient, ],
    "MessageText": text,
}
with open(os.path.join(SENT, datetime.datetime.now().isoformat().replace(':', '-')), 'w') as sentfile:
    sentfile.write(json.dumps(data, indent=2))
    res = requests.post(url, headers=headers, json=data, timeout=100)
    sentfile.write('\n\n')
    sentfile.write(res.text)

